# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG=colorplus
GOFILES=\
	calculations.go\
	colorspaces.go\
	colortypes.go\
	conversions.go\
	curves.go\
	filters.go\
	simple_filters.go\

# gb: this is the local install
GBROOT=.

# gb: compile/link against local install
GC+= -I $(GBROOT)/_obj
LD+= -L $(GBROOT)/_obj

package: $(GBROOT)/_obj/$(TARG).a

include $(GOROOT)/src/Make.pkg
